export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const CREATE_CUSTOMER_FAIL = "CREATE_CUSTOMER_FAIL";
export const SELECT_CUSTOMER = "SELECT_CUSTOMER";

export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER";
export const UPDATE_CUSTOMER_FAIL = "UPDATE_CUSTOMER_FAIL";

export const SEARCH_CUSTOMERS = "RETRIEVE_CUSTOMERS";
export const SEARCH_CUSTOMERS_SUCCESS = "SEARCH_CUSTOMERS_SUCCESS";
export const SEARCH_CUSTOMER_FAIL = "SEARCH_CUSTOMER_FAIL";

export const SEARCH_ORDERS_STARTED = "SEARCH_ORDERS_STARTED";
export const SEARCH_ORDERS_SUCCESS = "SEARCH_ORDERS_SUCCESS";
export const SEARCH_ORDERS_FAIL = "SEARCH_ORDERS_FAIL";

export const CREATE_ORDER_STARTED = "CREATE_ORDER_STARTED";
export const CREATE_ORDER_SUCCESS= "CREATE_ORDER_SUCCESS";;
export const CREATE_ORDER_FAIL= "CREATE_ORDER_FAIL";
export const SELECT_ORDER = "SELECT_ORDER";

export const RETRIEVE_ORDER_SUCCESS = "RETRIEVE_ORDER_SUCCESS";
export const RETRIEVE_ORDER_FAIL = "RETRIEVE_ORDER_FAIL";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";

export const RETRIEVE_SERVICES_SUCCESS = "RETRIEVE_SERVICES_SUCCESS";
export const RETRIEVE_SERVICES_FAIL = "RETRIEVE_SERVICES_FAIL";

export const LOADING_STARTED = "LOADING_STARTED";
export const LOADING_FINISHED = "LOADING_FINISHED";

export const RECEIVE_AUTH_TOKEN = "RECEIVE_AUTH_TOKEN";

